#!/bin/sh

RPATH=/local/renliang/imgRecSrc/beamharden
LPATH=.

for i in `seq $1 $2`
do
    scp research-$i:$RPATH/runIcip2014.mat $LPATH/runIcip2014_$i.mat
done

scp linux-3:$RPATH/runIcip2014.mat $LPATH/runIcip2014_l3.mat
scp linux-5:$RPATH/runIcip2014.mat $LPATH/runIcip2014_l5.mat

