#!/bin/sh

RPATH=/local/renliang/imgRecSrc/beamharden
LPATH=.
FILE=runAsilomar2014

for i in `seq $1 $2`
do
    scp research-$i:$RPATH/$FILE.mat $LPATH/$FILE\_$i.mat
done

for i in `seq $3 $4`
do
    scp linux-$i:$RPATH/$FILE.mat $LPATH/$FILE\_l$i.mat
done

